name: darted_cli
description: darted_cli is a customizable Dart CLI framework for building command-line tools with hierarchical command structures, argument parsing, and flag management.
version: 0.1.0
homepage: https://github.com/micazi/darted_cli

environment:
  sdk: ^3.4.0

dependencies:
  enough_ascii_art: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
